// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type NewTodo struct {
	Title string `json:"title"`
}

type Todo struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	Done  bool   `json:"done"`
}
