// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package api

import (
	"time"
)

type NewProgramCode struct {
	ToolID  string `json:"toolId"`
	Content string `json:"content"`
	Nrow    int    `json:"nrow"`
}

type NewTodo struct {
	Title string `json:"title"`
}

type PageInfo struct {
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	HasNextPage     bool    `json:"hasNextPage"`
}

type ProgramCode struct {
	ProgramCodeID string    `json:"programCodeId"`
	Content       string    `json:"content"`
	Nrow          int       `json:"nrow"`
	CreatedAt     time.Time `json:"createdAt"`
}

type ProgramCodeConnection struct {
	Edges    []*ProgramCodeEdge `json:"edges"`
	PageInfo *PageInfo          `json:"pageInfo"`
}

type ProgramCodeEdge struct {
	Node   *ProgramCode `json:"node"`
	Cursor string       `json:"cursor"`
}

type Todo struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	Done  bool   `json:"done"`
}
