// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package api

import (
	"time"
)

type Algorithm struct {
	AlgorithmID string `json:"algorithmId"`
	Name        string `json:"name"`
}

type AlgorithmCode struct {
	AlgorithmCodeID string    `json:"algorithmCodeId"`
	Content         string    `json:"content"`
	Nrow            int       `json:"nrow"`
	CreatedAt       time.Time `json:"createdAt"`
	LanguageID      string    `json:"languageId"`
	AlgorithmID     string    `json:"algorithmId"`
}

type FindAlgorithmCode struct {
	LanguageID  string `json:"languageId"`
	AlgorithmID string `json:"algorithmId"`
	StartRow    *int   `json:"startRow,omitempty"`
	EndRow      *int   `json:"endRow,omitempty"`
	Offset      *int   `json:"offset,omitempty"`
	Limit       *int   `json:"limit,omitempty"`
}

type FindPatternCode struct {
	LanguageID string `json:"languageId"`
	PatternID  string `json:"patternId"`
	StartRow   *int   `json:"startRow,omitempty"`
	EndRow     *int   `json:"endRow,omitempty"`
	Offset     *int   `json:"offset,omitempty"`
	Limit      *int   `json:"limit,omitempty"`
}

type FindProgramCode struct {
	ToolID   string `json:"toolId"`
	StartRow *int   `json:"startRow,omitempty"`
	EndRow   *int   `json:"endRow,omitempty"`
	Offset   *int   `json:"offset,omitempty"`
	Limit    *int   `json:"limit,omitempty"`
}

type Framework struct {
	FrameworkID string `json:"frameworkId"`
	Name        string `json:"name"`
}

type Language struct {
	LanguageID string `json:"languageId"`
	Name       string `json:"name"`
}

type NewAlgorithmCode struct {
	LanguageID  string `json:"languageId"`
	AlgorithmID string `json:"algorithmId"`
	Content     string `json:"content"`
}

type NewPatternCode struct {
	LanguageID string `json:"languageId"`
	PatternID  string `json:"patternId"`
	Content    string `json:"content"`
}

type NewProgramCode struct {
	ToolID  string `json:"toolId"`
	Content string `json:"content"`
}

type Pattern struct {
	PatternID string `json:"patternId"`
	Name      string `json:"name"`
}

type PatternCode struct {
	PatternCodeID string    `json:"patternCodeId"`
	Content       string    `json:"content"`
	Nrow          int       `json:"nrow"`
	CreatedAt     time.Time `json:"createdAt"`
	LanguageID    string    `json:"languageId"`
	PatternID     string    `json:"patternId"`
}

type ProgramCode struct {
	ProgramCodeID string    `json:"programCodeId"`
	Content       string    `json:"content"`
	Nrow          int       `json:"nrow"`
	CreatedAt     time.Time `json:"createdAt"`
	ToolID        string    `json:"toolId"`
}
